metrics:
  AdditionalObjects:
    -
      object_name: GNBCUUPFunction
      object_instance: CUUP_NumberOfMsgsSent
      expr: "CUUP_NumberOfMsgsSent"
      object_keys:
        -
          expr: "{{.labels.MessageType}}"
          name: MessageType
