{{- $cnfHdr := (dict "" "") -}} 
{{- include "cnfTplHeader_2_8" (dict "cnfHdr" $cnfHdr "dot" . ) -}}
apiVersion: apps/v1
kind: Deployment
{{- include "cnfTplMetadata_2_8" (dict "setOffset" "0" "cnfHdr" $cnfHdr "metadata" "") }}
spec:
  replicas: {{ .Values.componentSpec.deployment.replicas }}
  selector:
    matchLabels:
      app: iwfsvc
  serviceName: "iwfsvc"
  template:
    {{- include "cnfTplMetadata_2_8" (dict "setOffset" "4" "cnfHdr" $cnfHdr "metadata" .Values.componentSpec.deployment.pod_metaspec) }}
    spec:
      serviceAccountName: {{ $cnfHdr.nfVariables.svcname }}
      {{- if and (.Values.global) (.Values.global.cuup) (.Values.global.cuup.spNodeSelector) (.Values.global.cuup.spNodeSelector.enabled) }}
      nodeSelector:
        {{ .Values.global.cuup.spNodeSelector.labelKey }}: {{ .Values.global.cuup.spNodeSelector.labelValue | quote }}
      {{- end }}

      containers:
        -
          imagePullPolicy: Always
          {{- if and (.Values.global) (.Values.global.hub) (.Values.global.tag) }}
          image: {{ .Values.global.hub }}/{{.Values.componentSpec.deployment.us_iwfsvc.image}}:{{.Values.global.tag}}
          {{- else }}
          image: {{.Values.componentSpec.deployment.us_iwfsvc.hub}}/{{.Values.componentSpec.deployment.us_iwfsvc.image}}:{{.Values.componentSpec.deployment.us_iwfsvc.tag}}
          {{- end }}
          name: iwfsvc
          ports:
            - containerPort: {{ .Values.nf_variables.env_cfg.cim_port }}
              name: http
          tty: true
          volumeMounts:
            - mountPath: {{ .Values.nf_variables.env_cfg.config_root }}/{{ .Values.nf_variables.env_cfg.config_mgmt }}/common
              name: cuup-config-global
            - mountPath: {{ .Values.nf_variables.env_cfg.config_root }}/{{ .Values.nf_variables.env_cfg.config_mgmt }}/svc
              name: iwfsvc-config
            - mountPath: {{ .Values.nf_variables.env_cfg.config_root }}/{{ .Values.nf_variables.env_cfg.config_static }}/common
              name: cuup-config-static
          env:
            - name: CONFIG_ROOT
              value: {{ .Values.nf_variables.env_cfg.config_root }}
            - name: CONFIG_MGMT_ROOT
              value: {{ .Values.nf_variables.env_cfg.config_root }}/{{ .Values.nf_variables.env_cfg.config_mgmt }}
            - name: CONFIG_STATIC_ROOT
              value: {{ .Values.nf_variables.env_cfg.config_root }}/{{ .Values.nf_variables.env_cfg.config_static }}
            - name: CONFIG_CERT_ROOT
              value: {{ .Values.nf_variables.env_cfg.config_root }}/{{ .Values.nf_variables.env_cfg.cert_root }}
            - name: K8S_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: iwfsvc-v1-env-cfg
          resources:
            limits:
              cpu: {{ .Values.componentSpec.deployment.us_iwfsvc.resources.limits.cpu }}
              memory: {{ .Values.componentSpec.deployment.us_iwfsvc.resources.limits.memory }}
            requests:
              cpu: {{ .Values.componentSpec.deployment.us_iwfsvc.resources.requests.cpu }}
              memory: {{ .Values.componentSpec.deployment.us_iwfsvc.resources.requests.memory }}
          readinessProbe:
            exec:
              command:
              - cat
              - /data/readiness
            initialDelaySeconds: 5
            periodSeconds: 5              
        -
          command:
            - /bin/bash
            - -c
            - NatsSubFb
          env:
            - name: MS_CONFIG_REVISION
              valueFrom: 
                configMapKeyRef:
                  name: iwfsvc-v1-mgmt-cfg
                  key: revision
            - name: NF_CONFIG_REVISION
              valueFrom:
                configMapKeyRef:
                  name: cuup-v1-mgmt-cfg
                  key: revision
            - name: K8S_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MICROSERVICE_NAME
              value: {{ $cnfHdr.nfVariables.svcname }}
            - name: NF_PREFIX
              value: {{ $cnfHdr.nfVariables.nfPrefix }}
            - name: NF_TYPE
              value: {{ $cnfHdr.nfVariables.nfType }}
            - name: NF
              value: {{ $cnfHdr.nfVariables.nfName }}
          envFrom:
            - configMapRef:
                name: iwfsvc-v1-env-cfg
          {{- if (.Values.global) and (.Values.global.hub) }}
          image: {{ .Values.global.hub }}/{{.Values.componentSpec.deployment.us_cim.image}}:{{.Values.componentSpec.deployment.us_cim.tag}}
          {{- else }}
          image: {{.Values.componentSpec.deployment.us_cim.hub}}/{{.Values.componentSpec.deployment.us_cim.image}}:{{.Values.componentSpec.deployment.us_cim.tag}}
          {{- end }}
          imagePullPolicy: Always
          name: us-cim
          securityContext:
                  capabilities:
                          add:
                                  - NET_ADMIN
          tty: true
          volumeMounts:
            - mountPath: /config/global/
              name: cuup-config-global
            - mountPath: /config/mgmt/
              name: iwfsvc-config
            - mountPath: /config/cfg2
              name: iwfsvc-config-env
            - mountPath: /config/cfg_static
              name: cuup-config-static
            - name: mnt-log
              mountPath: {{ .Values.componentSpec.deployment.us_cim.mount.container_path }}
            - mountPath: /opt/conf/
              name: cim-config
            - mountPath: /opt/vipconf/
              name: mnt-vip-spec
            - mountPath: /opt/conf/static/
              name: mnt-common-infra
          resources:
            limits:
              memory: {{ .Values.componentSpec.deployment.us_cim.resources.limits.memory }}
              cpu: {{ .Values.componentSpec.deployment.us_cim.resources.limits.cpu }}
            requests:
              cpu: {{ .Values.componentSpec.deployment.us_cim.resources.requests.cpu }}
              memory: {{ .Values.componentSpec.deployment.us_cim.resources.requests.memory }}
      volumes:
        - configMap:
            name: iwfsvc-v1-mgmt-cfg
          name: iwfsvc-config
        - configMap:
            name: iwfsvc-v1-env-cfg
          name: iwfsvc-config-env
        - configMap:
            name: cuup-v1-mgmt-cfg
          name: cuup-config-global
        - configMap:
            name: cuup-v1-static-cfg
          name: cuup-config-static
        - configMap:
            items:
              - key: common-infra.json
                path: common-infra.json
            name: cuup-v1-static-cfg
          name: mnt-common-infra
        - configMap:
            items:
              - key: cim.json
                path: cim.json
            name: cuup-v1-mgmt-cfg
          name: cim-config
        - configMap:
            items:
              - key: vipspec.json
                path: vipspec.json
            name: cuup-v1-static-cfg
          name: mnt-vip-spec
        - name: mnt-log
          hostPath:
            path: {{ .Values.componentSpec.deployment.us_cim.mount.host_path }}
            type: {{ .Values.componentSpec.deployment.us_cim.mount.type }} 
