apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-1
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "enp0s10",
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "10.20.0.0/16",
                         "rangeStart": "10.20.1.20",
                         "rangeEnd": "10.20.3.50",
                         "gateway": "10.20.0.254"
                    } ]
                ]
            }
        }'