apiVersion: v1
kind: Pod
metadata:
    name: samplepod2
    annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf-1,macvlan-conf-1
spec:
    containers:
    - name: samplepod
      command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
      image: alpine
