apiVersion: apps/v1
kind: Deployment
metadata:
  name: testmacvlan-deployment
  labels:
    app: testmacvlan
 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testmacvlan
  template:
    metadata:
      labels:
        app: testmacvlan
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf-1
    spec:
      containers:
      - name: testmacvlan
        image: alpine
        command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]