apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-psql-0
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/psql/data-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jameszhang-virtualbox
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-psql-1
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/psql/data-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jameszhang-virtualbox
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-psql-2
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/psql/data-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jameszhang-virtualbox
