kind: PersistentVolumeClaim
apiVersion: v1
metadata:
        name: datadir-mypsql-0
spec:
        accessModes:
                - ReadWriteOnce
        volumeMode: Filesystem
        storageClassName: local-storage
        resources:
                requests:
                        storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
        name: datadir-mypsql-1
spec:
        accessModes:
                - ReadWriteOnce
        volumeMode: Filesystem
        storageClassName: local-storage
        resources:
                requests:
                        storage: 1Gi

---                        
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
        name: datadir-mypsql-2
spec:
        accessModes:
                - ReadWriteOnce
        volumeMode: Filesystem
        storageClassName: local-storage
        resources:
                requests:
                        storage: 1Gi
