{{- $cnfHdr := (dict "" "") -}}
{{- include "cnfTplHeader_2_8" (dict "cnfHdr" $cnfHdr "dot" . ) -}}
apiVersion: v1
kind: ServiceAccount
{{- include "cnfTplMetadata_2_8" (dict "setOffset" "0" "cnfHdr" $cnfHdr "metadata" "") }}

